// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using avaliacao_backend.Api.DbContexts;

namespace Api.Migrations
{
    [DbContext(typeof(AvaliacaoContext))]
    partial class AvaliacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("avaliacao_backend.Api.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Adequacao")
                        .HasColumnType("real");

                    b.Property<float>("ApresentacaoAdequada")
                        .HasColumnType("real");

                    b.Property<float>("ApresentacaoOral")
                        .HasColumnType("real");

                    b.Property<float>("AvaliacaoGeral")
                        .HasColumnType("real");

                    b.Property<float>("AvaliacaoResumo")
                        .HasColumnType("real");

                    b.Property<Guid>("CodigoAvaliador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodigoResumo")
                        .HasColumnType("uuid");

                    b.Property<float>("Coerencia")
                        .HasColumnType("real");

                    b.Property<float>("ContribuicaoComunidade")
                        .HasColumnType("real");

                    b.Property<float>("ContribuicaoDesenvolvimento")
                        .HasColumnType("real");

                    b.Property<int>("PremioTeixeira")
                        .HasColumnType("integer");

                    b.Property<float>("Qualidade")
                        .HasColumnType("real");

                    b.Property<float>("Relevancia")
                        .HasColumnType("real");

                    b.Property<float>("SomaDasNotas")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.ToTable("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
